### PR TITLE
Update es_es.json

### PR DESCRIPTION
**Pull request by FrannDzs**

### CODE REVIEW

**Comment by Azmalent** [comment]
It looks like you translated "Water Flag" literally, but it's actually a colloquial name for [Iris pseudacorus](https://en.wikipedia.org/wiki/Iris_pseudacorus) in English. I should probably add a comment for the translators.

Just wanted to clarify whether it's intended or not.

**Comment by FrannDzs** [comment]
Hello! Good morning! Yes, I did not know what to call it although searching the internet I found that the "bandera del* agua" is valid, but it could also be yellow flag or yellow iris flower. Now I correct that, thank you!

**Comment by FrannDzs** [comment]
@Azmalent Hi! how are you? I have a problem in "block.terraincognita.potted_dandelion_puff" and it happens that the translation is reset and appears in English. I already corrected it 2 times :(, I also don't know what puff means in this context, dandelion is dandelion potted is potted, but puff? my translations refer to ways of blowing with the mouth, for example: smoking a cigarette, inhaling, panting. Maybe the translation could be huge?.. Cheers!

**Comment by Azmalent** [comment]
Hey! Dandelion puff refers to a white fluffy dandelion. You could translate it as "white dandelion"
I have no clue why the translation is reset though.

**Comment by FrannDzs** [comment]
Thanks for the clarification, greetings!

**Pull request merged**
